In [21]:
import numpy as np
a = np.random.randint(0,21,size = 5)
a

array([ 5,  4, 12, 16,  8], dtype=int32)

In [22]:
a.shape #eleman sayısı


(5,)

In [23]:
a.ndim #boyutu

1

In [24]:
iki_boyutlu = np.array([[1,2,6,7],
[4,3,9,5]])
iki_boyutlu



array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [25]:
iki_boyutlu.shape # satır sütun eleman sayısı


(2, 4)

In [26]:
iki_boyutlu.size #eleman sayısı


8

In [27]:
iki_boyutlu.ndim # boyutu

2

In [28]:
uc_boyutlu = np.array([[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]])
uc_boyutlu


array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [29]:
uc_boyutlu.size #eleman sayısı


12

In [30]:
uc_boyutlu.shape # satır sütun derinlik eleman sayısı


(2, 2, 3)

In [31]:
uc_boyutlu.ndim # boyutu

3

In [32]:
print(iki_boyutlu[0][1]) # 2 elemanına ulaşmak için

2


In [33]:
print(iki_boyutlu[0][3]) # 7 elemanına ulaşmak için

7


In [34]:
print(uc_boyutlu[1][1][2]) # 9 elemanına ulaşmak için

9


In [35]:
print(uc_boyutlu[0][0][1]) # 5 elemanına ulaşmak için

5


In [36]:
print(iki_boyutlu[0,1:3])
print(iki_boyutlu[1,1:])

[2 6]
[3 9 5]


In [39]:
print(uc_boyutlu[0][1][0:])
print(uc_boyutlu[1][0][1:])

[21  8 11]
[ 6 20]


In [46]:
bir = np.ones((5,3), dtype = int)
print(bir)

sifir = np.zeros((5,3), dtype = int)
print(sifir)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [48]:
np.concatenate((bir, sifir))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])